import type React from "react";
import type { UIMessage, ChatStatus } from "ai";
import type {
  QuestionAnswer,
  QuestionConfig,
} from "./question/question-prompt";
import type { SuggestionItem } from "./input/suggestions";

export type InputSuggestions =
  | SuggestionItem[]
  | {
      items: SuggestionItem[];
      className?: string;
      itemClassName?: string;
    };

/** Theme JSON generated by the playground */
export type ChatTheme = {
  theme: Record<string, string>;
  light: Record<string, string>;
  dark: Record<string, string>;
};

/** Per-element CSS class overrides */
export type ChatClassNames = {
  root: string;
  userMessage: string;
  inputBar: string;
};

/** Props for createAgentChat() */
export type CreateAgentChatOptions = {
  agent: string;
  /** Provide either tokenUrl (simple) or getToken (full control) */
  tokenUrl?: string;
  getToken?: () => Promise<string>;
  apiUrl?: string;
  /**
   * Sandbox ID — identifies the persistent sandbox environment.
   *
   * Each unique `sandboxId` maps to its own sandbox (isolated VM with persistent filesystem).
   * Requests with the same `sandboxId` share the same sandbox — files, git repos,
   * and session history persist across messages.
   *
   * If omitted, the relay creates a new sandbox per request.
   *
   * @example
   * // Per-user sandbox
   * createAgentChat({ agent: "my-agent", tokenUrl: "/api/an/token", sandboxId: `user-${userId}` })
   *
   * // Continue existing sandbox
   * createAgentChat({ agent: "my-agent", tokenUrl: "/api/an/token", sandboxId: sandbox.id })
   */
  sandboxId?: string;
  /**
   * Thread ID — identifies a specific conversation thread within the sandbox.
   * Requires `sandboxId` to be set. If omitted with `sandboxId`, creates a new thread.
   */
  threadId?: string;
  onFinish?: () => void;
  onError?: (error: Error) => void;
};

/** Props passed to custom tool renderer components */
export type CustomToolRendererProps = {
  name: string;
  input: Record<string, unknown>;
  output: unknown | undefined;
  status: "pending" | "streaming" | "success" | "error";
};

/** Component slot overrides */
export type ChatSlots = {
  InputBar: React.ComponentType<{
    onSend: (message: { role: "user"; content: string }) => void;
    status: ChatStatus;
    onStop: () => void;
    [key: string]: unknown;
  }>;
  UserMessage: React.ComponentType<{
    message: UIMessage;
    className?: string;
  }>;
  ToolRenderer: React.ComponentType<{
    part: {
      type: string;
      toolCallId?: string;
      state?: string;
      input?: unknown;
      output?: unknown;
      result?: unknown;
    };
    nestedTools?: {
      type: string;
      toolCallId?: string;
      state?: string;
      input?: unknown;
      output?: unknown;
      result?: unknown;
    }[];
    chatStatus?: string;
    toolRenderers?: Record<
      string,
      React.ComponentType<CustomToolRendererProps>
    >;
  }>;
};

/** A model option for the model selector */
export type ModelOption = {
  id: string;
  name: string;
  version?: string;
};

/** Props for the <AgentChat> drop-in component */
export type AgentChatProps = {
  messages: UIMessage[];
  onSend: (message: { role: "user"; content: string }) => void;
  status: ChatStatus;
  onStop: () => void;
  error?: Error;

  classNames?: Partial<ChatClassNames>;
  slots?: Partial<ChatSlots>;
  toolRenderers?: Record<string, React.ComponentType<CustomToolRendererProps>>;

  /** Attachment configuration */
  attachments?: {
    onAttach?: () => void;
    images?: { id: string; filename: string; url: string; size?: number }[];
    files?: { id: string; filename: string; size?: number }[];
    onRemoveImage?: (id: string) => void;
    onRemoveFile?: (id: string) => void;
    onPaste?: (e: React.ClipboardEvent) => void;
    isDragOver?: boolean;
  };

  /** Show copy toolbar on text turns */
  showCopyToolbar?: boolean;

  /**
   * Where to position the scroll container on initial mount.
   * - "bottom" (default): classic chat behavior, pinned to the latest message.
   * - "top": start from the top of the conversation — useful for static demos
   *   or read-only transcripts where the user should read top-to-bottom.
   */
  initialScrollBehavior?: "bottom" | "top";

  /**
   * When true (default) clicking an attached image opens a fullscreen
   * lightbox preview. Set to false to render images as plain thumbnails
   * (no click handler, no portal). Applies to both staged input attachments
   * and images inside user messages.
   */
  enableImagePreview?: boolean;

  suggestions?: InputSuggestions;

  emptyStatePosition?: "default" | "center";
  emptySuggestionsPlacement?: "input" | "empty" | "both";
  emptySuggestionsPosition?: "top" | "bottom";

  questionTool?: {
    submitLabel?: string;
    skipLabel?: string;
    allowSkip?: boolean;
    onAnswer?: (payload: {
      toolCallId?: string;
      question: QuestionConfig;
      answer: QuestionAnswer;
    }) => void;
  };

  className?: string;
  style?: React.CSSProperties;
};

// Legacy type aliases kept for compatibility.
export type AnTheme = ChatTheme;
export type AnClassNames = ChatClassNames;
export type AnSlots = ChatSlots;
export type CreateAnChatOptions = CreateAgentChatOptions;
export type AnModelOption = ModelOption;
export type AnAgentChatProps = AgentChatProps;
